# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort

- repo: https://github.com/ambv/black
  rev: 22.10.0
  hooks:
    - id: black
      pass_filenames: true

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    pass_filenames: true

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v0.982'  # Use the sha / tag you want to point at
  hooks:
  -   id: mypy
